#Random suffix for uniqueness

resource "Random_id" "bucket_suffix" {
  byte_length = 8
  
}
#S3 Bucket for codecommit artifacts
#This bucket is used to store artifacts generated by CodeCommit such as build artifacts and test reports.
#The bucket name is generated by concatenating the project name with a random suffix.
#The ACL is set to private to restrict access to the bucket.
resource "aws_s3_bucket" "codecommit_bucket" {
  bucket = "${var.project_name}-codecommit-artifacts-${Random_id.bucket_suffix.hex}"
  acl    = "private"

  #The tags are used to identify the bucket.
  #The tags include the project name and a unique identifier.
  tags = { merge(var.tags, { Name = "${var.project_name}-codecommit-artifacts" }) }
        
  }
  
#S3 Bucket versioning
#Enables bucket versioning to allow multiple versions of artifacts to be stored.
#This is useful for rollback scenarios.
resource "aws_s3_bucket_versioning" "artifacts" {
    bucket = aws_s3_bucket.codecommit_bucket.id
    versioning_configuration {
      status = "Enabled"
    }
  }

#S3 Bucket encryption
#Enables server-side encryption to protect data at rest.
#Uses AES256 encryption algorithm.
resource "aws_s3_bucket_server_side_encryption_configuration" "artifacts" {
    bucket = aws_s3_bucket.codecommit_bucket.id
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }

  #S3 Bucket public access block
  #Blocks all public access to the bucket to enhance security.
  resource "aws_s3_bucket_public_access_block" "artifacts" {
    bucket = aws_s3_bucket.codecommit_bucket.id
    block_public_acls       = true
    block_public_policy     = true
    ignore_public_acls      = true
    restrict_public_buckets = true
  }
    #S3 Bucket lifecycle policy
    #Defines a lifecycle policy to transition objects to the STANDARD_IA storage class after 30 days.
    #This helps optimize storage costs for infrequently accessed artifacts.
resource "aws_s3_bucket_lifecycle_configuration" "artifacts" {
      bucket = aws_s3_bucket.codecommit_bucket.id
      rule {
        id     = "Delete old versions   of artifacts"
        status = "Enabled"
        expiration {
            days = 7
        }
        noncurrent_version_expiration {
            noncurrent_days = 7
        }
    }
  }
          